### ISSUE TITLE
2Jn.1.12 word order not following NA28

### ISSUE THREAD

**Issue by Andley** [tyndale/STEPBible-Data#52]
TAGNT: ἵνα 	ἡ 	χαρὰ 	ἡμῶν 	**πεπληρωμένη 	ᾖ**. 
NA: ἵνα ἡ χαρὰ ἡμῶν **ᾖ πεπληρωμένη**.

**Comment by DavidIB** [comment]
Thanks Andley

You are right that the word order is following the NA27 instead of the NA28
which changed it.
The alternate word order is recorded in the Editions data.
Whoops - I've just seen that it wasn't recorded - thanks for making me
look.
OK.. all fixed.
YOu can see that it says
[image: image.png]
![image](https://github.com/STEPBible/STEPBible-Data/assets/1691834/7ebf3811-2dc5-4f2a-ad57-57bfd70f100f)


This indicates that in NA28, Tyn, Treg, TR & Byz the word πεπληρωμένη
occurs after the next word,
but in NA27, SBL & WH it occurs in this order.

It was a tough decision to decide whether to follow NA27 or NA28 order.
There are very few places where it changes.
I decided to follow NA27 as the default Greek text because this is followed
by almost all modern Bibles - including those that claim to follow NA28.

Thanks for making me look!

*David IB*
